### ISSUE TITLE
수업 확인문제 질문드립니다 (143p_3번 문제)

### ISSUE THREAD

**Issue by PANDA-JOON** [newstars/hongongR#1]
3번 문제에서 i <- i + 1이 없어도 결과값이 5050으로 동일한데, 해당 구문이 함수에서 어떤 역할을 하는지 문의드려요

sum <- 0
for(i in 1:100) {
  sum <- sum + 1
  i <- i + 1 #해당 구문의 기능이 무엇인지 궁금합니다
}
cat(sum)

**Comment by newstars** [comment]
안녕하세요. 

이건 잘못된 코드가 맞습니다.

```
sum <- 0
for(i in 1:100) {
sum <- sum + 1
i <- i + 1 
}
cat(sum)
```

`i <- i + 1 `의 기능이 `for (i in 1:100)`으로 대체 됩니다.

`for (i in 100)` 일 경우 에 `i <- i + 1` 구문이 추가되어야 합니다.

감사합니다.

**Comment by PANDA-JOON** [comment]
이렇게 빠른 답변 기대를 못했는데 감사드려요!

for(i in 1:100)과 i <- i+1이 동일한 기능이라는 것으로 이해하면 될까요?

그리고 한가지 더 여쭤볼 것이 있는데요

말씀하신대로 구문을 작성해 보니
sum <- 0
for(i in 100){
  sum <- sum + i
  i <- i + 1
}
cat(sum)
실행값으로 100이 나옵니다

for 함수의 경우에는 반복횟수가 1:100 등으로 꼭 표현되어야 하는것 아닌가요?

**Comment by newstars** [comment]
제가 답을 잘못 적었네요.

다른 언어와 착각했습니다.

`for(i in 1:100)` 자체가 i가 1부터 100까지 라는 의미라서

`i <- i + 1` 가 중복된다는 의미 이며, 해당 부분은 삭제 해도 무방합니다.

```
sum <- 0
for(i in 1:100) {
sum <- sum + 1
}
cat(sum)
```

`for (i in 100)` 으로 할 경우에는 i는 100으로 만 연산되게 됩니다.


*제가 바로 보는 경우에는 바로 답변을 드리고 있습니다.^^;;
일하거나 그럴떈 힘들구요.

**Comment by PANDA-JOON** [comment]
답변 감사합니다!
