### ISSUE TITLE
반복적인 경고메시지 (파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못 되었습니다 

### ISSUE THREAD

**Issue by lnr3127** [newstars/hongongR#2]
안녕하세요?

최근에 노트북을 바꿔서 윈도우 10 설치했고 one drive에 자동으로 연결된 상태에서 R과 R studio를 설치했고, install.packages() 를 했는데 계속 오류가 떠서 구글 검색으로 권한을 허용해주니 패키지 설치는 됐습니다. 그런데 패키지를 로딩하려고 library(ggplot2)를 하면 'warning message: '파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못 되었습니다'라는 메시지가 반복적으로 뜨는데 해결방법을 문의 드립니다.

윈도우 계정이 한글로 되어 있는 경우 그럴 수 있다고 해서 확인해 보니 계정은 영어로 되어 있고, one drive가 문제일 수 있을 듯 해서 one drive도 삭제했습니다. 그리고 getwd( )해서 확인해 보니까 'c:/rstudy' 이런 식으로 되어 있는데 저 경고 메시지가 계속 뜨는 이유를 잘 모르겠네요. global option에서도 default 폴더는 d:/ 이렇게 되어 있습니다. ggplot2와 같은 패키지가 동작하기는 하는 것 같은데 반복해서 경고 메시지가 나와서 확인하려고 한 번 문의 드립니다. 

예전 노트북에 설치할 때는 별다른 문제없이 설치되었던 것 같은데 당황스럽네요. 모쪼록 아시는 분 도움 주시면 좋겠습니다. 참고차 화면 첨부 합니다. (중간에 색칠해 놓은 부분은 이름이라 지웠는데 영문 소문자로 되어 있습니다) 

미리 감사 드립니다!
[warning2](https://user-images.githubusercontent.com/48742570/161472070-19e9a5ad-48c6-4361-aa9f-fa2e83a2cb2a.png)

**Comment by newstars** [comment]
안녕하세요. 

해당 문제는 라이브러리 설치 문제 인것 같네요.

.libPaths()를 해보시면 라이브러리가 설치되어 있는 경로들이 보이실꺼에요.

잘 정리 되어있는 포스팅 공유해드립니다.
https://blog.naver.com/riry22/222332688068

감사합니다.
