### ISSUE TITLE
R 설치 후 실행이 안됩니다.

### ISSUE THREAD

**Issue by 0987pa** [newstars/hongongR#3]
![image](https://user-images.githubusercontent.com/104075662/164232623-9c2d575a-7596-4eaf-9dd1-cc17f099a560.png)
![image](https://user-images.githubusercontent.com/104075662/164232657-c1381a2c-e03b-4f9b-a0ff-1b8b1e8cc5dc.png)

안녕하세요 저자님! '처음 시작하는 R 데이터 분석' 책으로 입문을 했고
다시 처음부터 공부를 하고자 R과 R 스튜디오를 새로 설치했습니다.

다만, 설치하고 나서 R 프로그램 자체가 실행되지 않고,
R 스튜디오 또한 실행되지 않습니다.
혼자 해결해보려 했으나 해결되지 않아 질문 남깁니다.

이미지는 R 스튜디오를 실행했을때 뜨는 문구입니다.

**Comment by 0987pa** [comment]
프로그램을 꼭 써야해서 답변 부탁드리겠습니다! 감사합니다.

**Comment by newstars** [comment]
안녕하세요. 하단에 NEXT STEPS 으로 써있는 것처럼,
완전 다 삭제 하시고 재설치 해보셔야할 듯 합니다.

R이 설치 되어있지 않으면, R 스튜디오 역시 정상 구동 되지 않습니다.
