### ISSUE TITLE
R 스튜디오 클라우드에서 업로드 오류가 납니다

### ISSUE THREAD

**Issue by dev-Ock** [newstars/hongongR#4]
안녕하세요
유튜브 강의 혼공 R 5강을 보며 R스튜디오 클라우드에서 eng버전을 업로드하는데, 
Unexpected response from server 라는 error 메시지가 뜨는데 어떻게 해야하나요?

**Comment by newstars** [comment]
안녕하세요. 

1기가 가 넘을 경우 그런 문제가 발생되긴 하는데,
우선은 Rstudio Cloud 자체 오류인듯 합니다.

시간 지나고 다시 시도해보세요.

만약 안되시면 다른 곳에 파일을 올리고, curl 이나 wget 등으로 받아서 진행해야할듯 합니다.

**Comment by Trust2028** [comment]
안녕하세요, 
저도 r스튜디오 클라우드에서 알려주신대로 영어파일을 업로드하려고 하는데 계속 에러 메시지가 나옵니다. 
시간차를 두고 여러 차례 시도해봤지만 안되구요, "relaunch project" 버튼도 눌러봤지만 같은 상태입니다.
해결방법을 좀 쉽게 말씀해 주실수있을까요? 위에서 같은 질문을 남긴 분에게 답변주신 내용이 무슨 말인지 잘 모르겠어서 다시 질문드립니다.
