### ISSUE TITLE
p.213

### ISSUE THREAD

**Issue by kkkaa1** [newstars/hongongR#6]
r스튜디오에 
mutate(mtcars,years="1974")
mtcars
을 치면 years이 추가될거라고 생각했는데 mutate하기 전과 동일하게 years가 나오지 않아서 여쭤봅니다..
감사합니다

**Comment by newstars** [comment]
안녕하세요.

mtcars를 쳤을때 
mutate(mtcars, years = "1974") 의 결과 값처럼 나오지 않는다는 말인가요?

이건 변수로 저장을 하셔야 가능합니다.

a <- mutate(mtcars, years = "1974")
a

라고 하면 원하는 결과가 나올꺼에요.
