### ISSUE TITLE
lavaan 패키지 오류 관련하여 문의드립니다

### ISSUE THREAD

**Issue by sangsang00** [newstars/hongongR#7]
안녕하세요^^ R을 활용하여 SEM 분석을 하다가 오류가 발생해서 해결방법을 찾던 중 'R에서 코드 오류를 해결하는 4가지 방법' 동영상을 보게 되었습니다.
감사하게도 질문할 수 있는 통로를 열어주셔서 많이 바쁘시겠지만 제 질문도 답변해주시지 않을까 싶어 문의드립니다.
다음 코드를 바탕으로 분석하고 있는데 두 가지 질문이 있습니다.

1. CFA까지는 잘 되는데, 구조모형을 돌리면 
Error in lavaan::lavaan(model = sr.model, data = data1, model.type = "sem",  : 
  lavaan ERROR: missing observed variables in dataset: social
이런 에러 메세지가 나옵니다. 어떻게 해야할까요?

2. 처음 데이터를 불러올때도 data1 <- read.csv("simple_data1.csv") 이렇게만 설정하면 오류가 나서 구글링으로 인코딩 수정하는 문구를 추가해서 불러왔는데요, 원인이 무엇인지 궁금합니다. 방지할 수 있는 방법은 없을지요?

3. 코딩은 아래와 같습니다.

library(lavaan)

data1 <- read.csv("simple_data1.csv", na = "-", fileEncoding = "CP949", encoding = "UTF-8")
str(data1)
head(data1)
dim(data1)

#step1-cfa analysis

cfa.model <- 
  'cog =~ FAC1+FAC2
   facil =~ FAC3+FAC4
   trust =~ T1+T2
   rule =~ Q2_8_1+Q2_8_2+Q2_8_3
   social =~ sol1+sol2'
cfa.out <- cfa(cfa.model, data1)
summary(cfa.out, fit.measures=T, standardized=T)

library(semPlot)
semPaths(cfa.out)
semPaths(cfa.out, style="lisrel")

#step2-SR

sr.model <- 
  'cog =~ FAC1+FAC2
   facil =~ FAC3+FAC4
   trust =~ T1+T2
   rule =~ Q2_8_1+Q2_8_2+Q2_8_3
   socail =~ sol1+sol2
   trust ~ cog+facil
   rule ~ cog+facil
   social ~ cog+facil+rule+trust'
  
sr.out <- sem(sr.model, data1)
summary(sr.out, fit.measures=T, standardized=T)
summary(sr.out, fit.measures=T, standardized=T, rsquare=T)

그럼, 확인 부탁드립니다. 
감사합니다^^

**Comment by newstars** [comment]
안녕하세요. 

제가 휴가 중이라서 확인이 늦었습니다.

해결 하셨나 보네요.

**Comment by sangsang00** [comment]
안녕하세요, 휴일에도 관심갖고 확인해주셔서 감사합니다.
다행히 오타를 찾아서 모형 분석은 할 수 있었습니다^^

그런데 여전히 2번 질문에 대해서는 의문이 남는데 여쭤봐도 될지요?
csv 파일로 저장했는데 불러오지 못하는 이유와 방지할 수 있는 방법이 궁금합니다.
감사합니다!

**Comment by newstars** [comment]
올려주신 csv 파일을 보면 저도 깨져서 나오는데요.

아시겠지만, 기본적으로는 CSV 파일과 R의 기본 인코딩이 다르기 때문이에요.

일단 제일 좋은 것은 데이터에서 한글을 안 쓰는 것이고. 
MS 같은경우는 코드에도 쓰셨다시피 EUC_KR 이 아닌 완성형한글인 CP949를 쓰고 있구요.

CSV 파일을 내렸을때, 인코딩이 멀로 되어있는지 확인이 필요합니다.

또한 CSV의 경우에는 TEXT 기 때문에 다른 파일 포멧을 쓰는것도 좋을듯 합니다.

감사합니다.

**Comment by sangsang00** [comment]
친절한 답변 너무 감사드립니다^^ 다가오는 추석연휴도 즐겁게 보내시고 늘 건강하세요~
