### ISSUE TITLE
readxl 패키지 설치가 안됩니다. 

### ISSUE THREAD

**Issue by somerset27** [newstars/hongongR#8]
**현재 맥북으로 Rstudio를 사용 중에 있으며, 버전 2022.12.0+353(2022.12.0+353) 입니다. 
   참고로, Mac OS 버전은 Ventura 13.2.1 입니다. 

readxl 패키지 설치 입력시 아래와 같은 문구가 나오는데, 어떻게 해결해야 할까요?**

> install.packages('readxl')
Warning in install.packages :
  cannot open compressed file '/var/folders/0s/kcbqrfr57hxg3ykt6y4kzz_m0000gn/T//RtmpoVgyPS/repos_https%3A%2F%2Fcran.rstudio.com%2Fsrc%2Fcontrib.rds', probable reason 'No such file or directory'
Warning in install.packages :
  cannot open compressed file '/var/folders/0s/kcbqrfr57hxg3ykt6y4kzz_m0000gn/T//RtmpoVgyPS/file2a587ee1fae9', probable reason 'No such file or directory'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open the connection
Warning in install.packages :
  cannot open compressed file '/var/folders/0s/kcbqrfr57hxg3ykt6y4kzz_m0000gn/T//RtmpoVgyPS/repos_https%3A%2F%2Fcran.rstudio.com%2Fsrc%2Fcontrib.rds', probable reason 'No such file or directory'
Warning in install.packages :
  cannot open compressed file '/var/folders/0s/kcbqrfr57hxg3ykt6y4kzz_m0000gn/T//RtmpoVgyPS/file2a5826201813', probable reason 'No such file or directory'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open the connection
Warning in install.packages :
  package ‘readxl’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  cannot open compressed file '/var/folders/0s/kcbqrfr57hxg3ykt6y4kzz_m0000gn/T//RtmpoVgyPS/repos_https%3A%2F%2Fcran.rstudio.com%2Fbin%2Fmacosx%2Fbig-sur-arm64%2Fcontrib%2F4.2.rds', probable reason 'No such file or directory'
Warning in install.packages :
  cannot open compressed file '/var/folders/0s/kcbqrfr57hxg3ykt6y4kzz_m0000gn/T//RtmpoVgyPS/file2a5850c9af3', probable reason 'No such file or directory'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2:
  cannot open the connection

**Comment by somerset27** [comment]
descr, psych 패키지도 다 같은 이유로 설치가 안되는데.. 제 R studio 프로그램에 문제가 있는걸까요?
아님 제가 뭘 잘못한 걸까요?

**Comment by newstars** [comment]
메일로 회신드렸습니다.
