### ISSUE TITLE
외부데이터 불러오기에 대해

### ISSUE THREAD

**Issue by K-Y-U** [newstars/hongongR#9]
ex_data <- read.table("/Users/seong/Desktop/data_ex.txt", encoding = "EUC-KR",
                      fileEncoding = "UTF-8", col.names = varname) 
을 입력 후 Error에 외부데이터를 가져올 수 없다고 하는데... 모르겠네요.. 구글링 하면서 맥북 관련 파일 위치 저장도 했는데 계속 오류가 나오네요...
오류 메세지는 
Error in file(file, "rt", encoding = fileEncoding) : 
  cannot open the connection
In addition: Warning message:
In file(file, "rt", encoding = fileEncoding) :
  cannot open file '/Users/seong/Desktop/data_ex.txt': No such file or directory
원인을 모르겠습니다ㅠㅠ

**Comment by newstars** [comment]
안녕하세요. 

원인은 파일이 위치하지 않는다고 되어있는데요.

cannot open file '/Users/seong/Desktop/data_ex.txt': No such file or directory

파일 위치 확인 부탁드려요.
